package org.dragon.datasource.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

import org.dragon.workspace.member.CharacterDuty;

/**
 * CharacterDutyEntity Character职责实体
 * 映射数据库 character_duty 表
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "character_duty")
public class CharacterDutyEntity {

    @Id
    private String id;

    private String workspaceId;

    private String characterId;

    private String dutyDescription;

    private boolean autoGenerated;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    /**
     * 转换为CharacterDuty
     */
    public CharacterDuty toCharacterDuty() {
        return CharacterDuty.builder()
                .id(this.id)
                .workspaceId(this.workspaceId)
                .characterId(this.characterId)
                .dutyDescription(this.dutyDescription)
                .autoGenerated(this.autoGenerated)
                .createdAt(this.createdAt)
                .updatedAt(this.updatedAt)
                .build();
    }

    /**
     * 从CharacterDuty创建Entity
     */
    public static CharacterDutyEntity fromCharacterDuty(CharacterDuty duty) {
        return CharacterDutyEntity.builder()
                .id(duty.getId())
                .workspaceId(duty.getWorkspaceId())
                .characterId(duty.getCharacterId())
                .dutyDescription(duty.getDutyDescription())
                .autoGenerated(duty.isAutoGenerated())
                .createdAt(duty.getCreatedAt())
                .updatedAt(duty.getUpdatedAt())
                .build();
    }
}
